// Generated by Void Manifest Engine
// List all sutras, with optional search and category filter

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

import type { GetSutraInput } from '@/types'

export async function get(request: NextRequest) {
  const body = await request.json()
  // TODO: Add Zod validation for input schema

  // Fetch sutras from database. If query param 'search' is provided, filter by title or englishMeaning containing the search string (case-insensitive). If query param 'category' is provided, filter by category. Return array of sutra objects (id, title, sanskritText, englishMeaning, category).

  const items = await prisma.Sutra.findMany()
  return NextResponse.json(items)
}