// Generated by Void Manifest Engine
// Sutra Detail

import SutraDetail from '@/components/SutraDetail'
import RelatedSutras from '@/components/RelatedSutras'

export default function SutraDetailPage() {
  return (
    <main className="container mx-auto p-4">
      <h1 className="text-2xl font-bold">Sutra Detail</h1>
      <p className="text-gray-600 mt-2">Detail page for a single sutra with related sutras</p>
      <SutraDetail />
      <RelatedSutras />
    </main>
  )
}