// Generated by Void Manifest Engine
// Get a single sutra by ID, including related sutras

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

import type { GetSutraInput } from '@/types'

export async function get(request: NextRequest) {
  const body = await request.json()
  // TODO: Add Zod validation for input schema

  // Fetch sutra by ID. Also fetch related sutras via SutraRelation table (both directions). Return sutra object with an array of related sutras (each with id, title, category).

  const id = request.nextUrl.pathname.split('/').pop()
  const item = await prisma.Sutra.findUnique({ where: { id } })
  if (!item) return NextResponse.json({ error: 'Not found' }, { status: 404 })
  return NextResponse.json(item)
}