// Generated by Void Manifest Engine
// List all available categories

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function get(request: NextRequest) {
  // Return a static list of categories: ['Cosmology', 'Mind', 'Practice', 'Self', 'Creation']

  // Route: GET /api/categories
  // Handler logic: Return a static list of categories: ['Cosmology', 'Mind', 'Practice', 'Self', 'Creation']
  return NextResponse.json({ message: 'Implement Return a static list of categories: ['Cosmology', ...' })
}