"""Manifest Engine — deterministic compiler from ArchitecturalGraph to code files.

This is Step 3 of the Puranic creation model: the Conscious Void (ArchitecturalGraph)
is rendered into working code files. No LLM. No generation. Pure compilation.

Given the same graph, it produces the same code. Every time. Zero hallucination.
"""
from __future__ import annotations

import os
from typing import Dict, List

from tools.void_manifest.arch_schema import (
    ArchitecturalGraph, EntityDef, ComponentDef, RouteDef, PageDef,
    FieldType, RelationType, ComponentType, AuthType, HttpMethod,
    _to_snake, _to_camel,
)


def render(graph: ArchitecturalGraph, output_dir: str) -> Dict[str, str]:
    """Compile the Architectural Graph into code files.

    Returns {relative_path: file_content} dict. Does NOT write to disk —
    call write_files() to persist.

    Target stack: Next.js 14+ (App Router) + TypeScript + Prisma + Tailwind.
    """
    files: Dict[str, str] = {}

    # ── Database schema ──────────────────────────────────────────────────
    if graph.app.stack == "nextjs":
        files["prisma/schema.prisma"] = _render_prisma_schema(graph)
        files["src/lib/prisma.ts"] = _render_prisma_client()

    # ── TypeScript types ─────────────────────────────────────────────────
    files["src/types/index.ts"] = _render_types(graph)

    # ── API routes ───────────────────────────────────────────────────────
    for route in graph.routes:
        route_path = _route_to_filepath(route.path, route.method)
        files[f"src/app/api{route_path}/route.ts"] = _render_route(route, graph)

    # ── Auth middleware ──────────────────────────────────────────────────
    if graph.auth.type != AuthType.NONE:
        files["src/lib/auth.ts"] = _render_auth(graph)

    # ── Components ───────────────────────────────────────────────────────
    for comp in graph.components:
        if comp.type not in (ComponentType.PAGE, ComponentType.LAYOUT):
            files[f"src/components/{comp.name}.tsx"] = _render_component(comp, graph)

    # ── Pages ────────────────────────────────────────────────────────────
    for page in graph.pages:
        page_dir = _page_to_dir(page.path)
        files[f"src/app{page_dir}/page.tsx"] = _render_page(page, graph)

    # ── Root layout ─────────────────────────────────────────────────────
    files["src/app/layout.tsx"] = _render_root_layout(graph)

    # ── Package.json ────────────────────────────────────────────────────
    files["package.json"] = _render_package_json(graph)

    # ── Environment ──────────────────────────────────────────────────────
    files[".env.local.example"] = _render_env(graph)

    # ── README ───────────────────────────────────────────────────────────
    files["README.md"] = _render_readme(graph)

    return files


def write_files(files: Dict[str, str], output_dir: str) -> List[str]:
    """Write rendered files to disk. Creates directories as needed."""
    written = []
    for rel_path, content in files.items():
        full_path = os.path.join(output_dir, rel_path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w") as f:
            f.write(content)
        written.append(rel_path)
    return written


# ─── Renderers ────────────────────────────────────────────────────────────────

def _render_prisma_schema(graph: ArchitecturalGraph) -> str:
    """Generate Prisma schema from entity definitions."""
    lines = [
        "// Generated by Void Manifest Engine",
        "// DO NOT EDIT BY HAND — regenerate from the Architectural Graph",
        "",
        'datasource db {',
        '  provider = "postgresql"',
        '  url      = env("DATABASE_URL")',
        "}",
        "",
        'generator client {',
        '  provider = "prisma-client-js"',
        "}",
        "",
    ]

    for e in graph.entities:
        lines.append(f"model {e.name} {{")
        existing_fields = {f.name for f in e.fields}
        for f in e.fields:
            prisma_type = _field_to_prisma(f.type)
            attrs = ""
            if f.name == "id" and f.type == FieldType.INTEGER:
                attrs = " @id @default(autoincrement())"
            elif f.name == "id" and f.type == FieldType.STRING:
                attrs = ' @id @default(uuid())'
            if f.unique and "id" not in attrs:
                attrs += " @unique"
            if f.type == FieldType.EMAIL:
                attrs += " @unique" if "unique" not in attrs else ""
            required = "" if f.required else "?"
            default_str = ""
            if f.default is not None:
                if isinstance(f.default, str):
                    default_str = f' @default("{f.default}")'
                elif isinstance(f.default, bool):
                    default_str = f" @default({str(f.default).lower()})"
                else:
                    default_str = f" @default({f.default})"
            lines.append(f"  {f.name} {prisma_type}{required}{default_str}{attrs}")

        # Relations — only add FK fields that don't already exist
        for r in e.relations:
            if r.type == RelationType.BELONGS_TO:
                fk = r.foreign_key or f"{_to_snake(r.target)}_id"
                if fk not in existing_fields:
                    target = _find_entity(graph, r.target)
                    id_field = _find_id_field(target)
                    fk_type = _field_to_prisma(id_field.type) if id_field else "Int"
                    lines.append(f"  {fk} {fk_type}")
                lines.append(f"  {_to_camel(r.target)} {r.target} @relation(fields: [{fk}], references: [id])")
            elif r.type == RelationType.HAS_MANY:
                plural = _pluralize(r.target)
                lines.append(f"  {_to_camel(plural)} {r.target}[]")
            elif r.type == RelationType.HAS_ONE:
                lines.append(f"  {_to_camel(r.target)} {r.target}?")

        # Timestamps — only add if the entity doesn't define them
        if "createdAt" not in existing_fields:
            lines.append("  createdAt DateTime @default(now())")
        if "updatedAt" not in existing_fields:
            lines.append("  updatedAt DateTime @updatedAt")

        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def _render_prisma_client() -> str:
    return """import { PrismaClient } from '@prisma/client'

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient }

export const prisma = globalForPrisma.prisma || new PrismaClient()

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma
"""


def _render_types(graph: ArchitecturalGraph) -> str:
    """Generate TypeScript types from entity definitions."""
    lines = [
        "// Generated by Void Manifest Engine",
        "// DO NOT EDIT BY HAND",
        "",
    ]
    for e in graph.entities:
        lines.append(f"export interface {e.name} {{")
        for f in e.fields:
            ts_type = _field_to_typescript(f.type)
            optional = "" if f.required else "?"
            lines.append(f"  {f.name}{optional}: {ts_type}")
        # Include relation fields
        for r in e.relations:
            if r.type == RelationType.BELONGS_TO:
                fk = r.foreign_key or f"{_to_snake(r.target)}_id"
                lines.append(f"  {fk}: string")
                lines.append(f"  {_to_camel(r.target)}?: {r.target}")
            elif r.type == RelationType.HAS_MANY:
                lines.append(f"  {_to_camel(r.target)}s?: {r.target}[]")
            elif r.type == RelationType.HAS_ONE:
                lines.append(f"  {_to_camel(r.target)}?: {r.target}")
        lines.append(f"  createdAt: Date")
        lines.append(f"  updatedAt: Date")
        lines.append("}")
        lines.append("")

    # API types
    lines.append("// API request/response types")
    for route in graph.routes:
        if route.input_schema:
            type_name = _route_to_type_name(route) + "Input"
            lines.append(f"export interface {type_name} {{")
            for field_name, field_info in route.input_schema.get("properties", {}).items():
                ts_type = _json_schema_to_ts(field_info)
                required_fields = route.input_schema.get("required", [])
                optional = "" if field_name in required_fields else "?"
                lines.append(f"  {field_name}{optional}: {ts_type}")
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def _render_route(route: RouteDef, graph: ArchitecturalGraph) -> str:
    """Generate a Next.js App Router API route handler."""
    method_lower = route.method.value.lower()
    type_name = _route_to_type_name(route)

    lines = [
        "// Generated by Void Manifest Engine",
        f"// {route.description}",
        "",
        "import { NextRequest, NextResponse } from 'next/server'",
    ]
    if graph.auth.type != AuthType.NONE and route.auth_required:
        lines.append("import { authenticate } from '@/lib/auth'")
    lines.append("import { prisma } from '@/lib/prisma'")
    lines.append("")

    has_input = bool(route.input_schema.get("properties"))
    if has_input:
        lines.append(f"import type {{ {type_name}Input }} from '@/types'")
        lines.append("")

    # Handler function
    lines.append(f"export async function {method_lower}(request: NextRequest) {{")
    if route.auth_required and graph.auth.type != AuthType.NONE:
        lines.append("  const user = await authenticate(request)")
        lines.append("  if (!user) {")
        lines.append("    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })")
        lines.append("  }")
        lines.append("")

    if has_input:
        lines.append("  const body = await request.json()")
        lines.append("  // TODO: Add Zod validation for input schema")
        lines.append("")

    # Handler logic — rendered as structured comments guiding the dev
    if route.handler_logic:
        lines.append(f"  // {route.handler_logic}")
        lines.append("")

    # Generate CRUD boilerplate based on pattern matching
    entity = _guess_entity_from_route(route, graph)
    if entity:
        if route.method == HttpMethod.GET and "/:" not in route.path:
            lines.append(f"  const items = await prisma.{_to_camel(entity.name)}.findMany()")
            lines.append(f"  return NextResponse.json(items)")
        elif route.method == HttpMethod.GET:
            lines.append(f"  const id = request.nextUrl.pathname.split('/').pop()")
            lines.append(f"  const item = await prisma.{_to_camel(entity.name)}.findUnique({{ where: {{ id }} }})")
            lines.append(f"  if (!item) return NextResponse.json({{ error: 'Not found' }}, {{ status: 404 }})")
            lines.append(f"  return NextResponse.json(item)")
        elif route.method == HttpMethod.POST:
            lines.append(f"  const item = await prisma.{_to_camel(entity.name)}.create({{ data: body }})")
            lines.append(f"  return NextResponse.json(item, {{ status: 201 }})")
        elif route.method == HttpMethod.PUT or route.method == HttpMethod.PATCH:
            lines.append(f"  const id = request.nextUrl.pathname.split('/').pop()")
            lines.append(f"  const item = await prisma.{_to_camel(entity.name)}.update({{ where: {{ id }}, data: body }})")
            lines.append(f"  return NextResponse.json(item)")
        elif route.method == HttpMethod.DELETE:
            lines.append(f"  const id = request.nextUrl.pathname.split('/').pop()")
            lines.append(f"  await prisma.{_to_camel(entity.name)}.delete({{ where: {{ id }} }})")
            lines.append(f"  return NextResponse.json({{ success: true }})")
    else:
        lines.append(f"  // Route: {route.method.value} {route.path}")
        lines.append(f"  // Handler logic: {route.handler_logic}")
        lines.append(f"  return NextResponse.json({{ message: 'Implement {route.handler_logic[:50]}...' }})")

    lines.append("}")
    return "\n".join(lines)


def _render_auth(graph: ArchitecturalGraph) -> str:
    """Generate auth middleware."""
    return f"""// Generated by Void Manifest Engine
import {{ NextRequest }} from 'next/server'
import {{ jwtVerify }} from 'jose'

const JWT_SECRET = new TextEncoder().encode(process.env.JWT_SECRET || 'dev-secret-change-me')

export async function authenticate(request: NextRequest) {{
  const token = request.headers.get('{graph.auth.token_field}')?.replace('Bearer ', '')
  if (!token) return null
  try {{
    const {{ payload }} = await jwtVerify(token, JWT_SECRET)
    return payload as {{ sub: string; role: string }}
  }} catch {{
    return null
  }}
}}

export function requireRole(user: any, ...roles: string[]) {{
  if (!user) return false
  return roles.length === 0 || roles.includes(user.role)
}}
"""


def _render_component(comp: ComponentDef, graph: ArchitecturalGraph) -> str:
    """Generate a React component."""
    lines = [
        "// Generated by Void Manifest Engine",
        f"// {comp.description}",
        "",
        "'use client'",
        "",
        "import { useState } from 'react'",
        "",
    ]

    # Props type
    if comp.props:
        lines.append(f"interface {comp.name}Props {{")
        for prop in comp.props:
            ptype = _normalize_ts_type(str(prop.get("type", "any")))
            optional = "" if prop.get("required", False) else "?"
            lines.append(f"  {prop['name']}{optional}: {ptype}")
        lines.append("}")
        lines.append("")

    # Component
    props_destructure = ""
    if comp.props:
        prop_names = [p["name"] for p in comp.props]
        props_destructure = "{ " + ", ".join(prop_names) + " }"

    if comp.props:
        lines.append(f"export default function {comp.name}({props_destructure}: {comp.name}Props) {{")
    else:
        lines.append(f"export default function {comp.name}() {{")

    # State
    for s in comp.state:
        default_val = _format_default(s.get("default"))
        stype = _normalize_ts_type(str(s.get("type", "any")))
        lines.append(f"  const [{s['name']}, set{_capitalize(s['name'])}] = useState<{stype}>({default_val})")

    if comp.type == ComponentType.FORM:
        lines.append("")
        lines.append(f"  const handleSubmit = async (e: React.FormEvent) => {{")
        lines.append("    e.preventDefault()")
        lines.append("    // TODO: Wire to API route")
        lines.append("  }}")
        lines.append("")
        lines.append("  return (")
        lines.append(f'    <form onSubmit={{handleSubmit}} className="space-y-4">')
        if comp.props:
            for prop in comp.props:
                lines.append(f"      <div>")
                lines.append(f'        <label className="block text-sm font-medium">{prop["name"]}</label>')
                input_type = "email" if "email" in prop["name"].lower() else "text"
                lines.append(f'        <input type="{input_type}" className="mt-1 block w-full rounded border p-2" />')
                lines.append(f"      </div>")
        lines.append(f'      <button type="submit" className="rounded bg-blue-600 px-4 py-2 text-white">Submit</button>')
        lines.append(f"    </form>")
        lines.append("  )")

    elif comp.type == ComponentType.CARD:
        lines.append("  return (")
        lines.append(f'    <div className="rounded-lg border p-4 shadow-sm">')
        lines.append(f"      {{/* {comp.description} */}}")
        if comp.props:
            for prop in comp.props:
                lines.append(f"      {{/* {prop['name']}: {{{prop['name']}}} */}}")
        lines.append(f"    </div>")
        lines.append("  )")

    elif comp.type == ComponentType.LIST:
        lines.append("  return (")
        lines.append(f'    <div className="space-y-2">')
        lines.append(f"      {{/* Iterate over items */}}")
        lines.append(f"    </div>")
        lines.append("  )")

    else:
        lines.append("  return (")
        lines.append(f'    <div>')
        lines.append(f"      {{/* {comp.name}: {comp.description} */}}")
        lines.append(f"    </div>")
        lines.append("  )")

    lines.append("}")
    return "\n".join(lines)


def _render_page(page: PageDef, graph: ArchitecturalGraph) -> str:
    """Generate a Next.js page."""
    lines = [
        "// Generated by Void Manifest Engine",
        f"// {page.title}",
        "",
    ]
    if page.auth_required:
        lines.append("import { redirect } from 'next/navigation'")
        lines.append("import { authenticate } from '@/lib/auth'")
        lines.append("")

    # Import components used on this page
    for cname in page.components:
        comp = _find_component(graph, cname)
        if comp and comp.type not in (ComponentType.PAGE, ComponentType.LAYOUT):
            lines.append(f"import {cname} from '@/components/{cname}'")
    lines.append("")

    if page.auth_required:
        lines.append(f"export default async function {_page_to_component_name(page)}() {{")
        lines.append("  const user = await authenticate(/* request */)")
        lines.append("  if (!user) redirect('/login')")
        lines.append("")
    else:
        lines.append(f"export default function {_page_to_component_name(page)}() {{")

    lines.append("  return (")
    lines.append(f'    <main className="container mx-auto p-4">')
    lines.append(f"      <h1 className=\"text-2xl font-bold\">{page.title}</h1>")

    if page.description:
        lines.append(f"      <p className=\"text-gray-600 mt-2\">{page.description}</p>")

    # Render components
    for cname in page.components:
        lines.append(f"      <{cname} />")

    lines.append(f"    </main>")
    lines.append("  )")
    lines.append("}")
    return "\n".join(lines)


def _render_root_layout(graph: ArchitecturalGraph) -> str:
    """Generate root layout.tsx."""
    return f"""// Generated by Void Manifest Engine
import type {{ Metadata }} from 'next'
import './globals.css'

export const metadata: Metadata = {{
  title: '{graph.app.name}',
  description: '{graph.app.description}',
}}

export default function RootLayout({{
  children,
}}: {{
  children: React.ReactNode
}}) {{
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-gray-900">
        {{children}}
      </body>
    </html>
  )
}}
"""


def _render_package_json(graph: ArchitecturalGraph) -> str:
    """Generate package.json."""
    import json
    pkg = {
        "name": _to_snake(graph.app.name),
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint",
            "db:push": "prisma db push",
            "db:generate": "prisma generate",
        },
        "dependencies": {
            "next": "^14.0.0",
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "@prisma/client": "^5.0.0",
        },
        "devDependencies": {
            "typescript": "^5.0.0",
            "@types/react": "^18.0.0",
            "@types/node": "^20.0.0",
            "prisma": "^5.0.0",
            "tailwindcss": "^3.0.0",
            "autoprefixer": "^10.0.0",
            "postcss": "^8.0.0",
        },
    }
    if graph.auth.type == AuthType.JWT:
        pkg["dependencies"]["jose"] = "^5.0.0"

    return json.dumps(pkg, indent=2)


def _render_env(graph: ArchitecturalGraph) -> str:
    lines = [
        "# Generated by Void Manifest Engine",
        f"# {graph.app.name} — Environment Variables",
        "",
        'DATABASE_URL="postgresql://postgres:postgres@localhost:5432/' + _to_snake(graph.app.name) + '"',
    ]
    if graph.auth.type == AuthType.JWT:
        lines.append('JWT_SECRET="change-me-to-a-random-secret"')
    return "\n".join(lines) + "\n"


def _render_readme(graph: ArchitecturalGraph) -> str:
    lines = [
        f"# {graph.app.name}",
        "",
        f"> Generated by Void Manifest Engine — {graph.app.description}",
        "",
        "## Getting Started",
        "",
        "```bash",
        "npm install",
        "npx prisma db push",
        "npm run dev",
        "```",
        "",
        "## Architecture",
        "",
        f"- **Stack:** {graph.app.stack}",
        f"- **Entities:** {', '.join(e.name for e in graph.entities)}",
        f"- **Routes:** {len(graph.routes)} endpoints",
        f"- **Pages:** {len(graph.pages)} pages",
        f"- **Components:** {len(graph.components)} components",
        f"- **Auth:** {graph.auth.type.value}",
        "",
    ]
    if graph.entities:
        lines.append("### Data Model")
        for e in graph.entities:
            lines.append(f"- **{e.name}** — {e.description or 'No description'}")
            for f in e.fields:
                lines.append(f"  - {f.name}: {f.type.value}{' (required)' if f.required else ''}")
        lines.append("")

    if graph.routes:
        lines.append("### API Routes")
        for r in graph.routes:
            auth = " 🔒" if r.auth_required else ""
            lines.append(f"- `{r.method.value} {r.path}`{auth} — {r.description}")
        lines.append("")

    return "\n".join(lines)


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _field_to_prisma(ftype: FieldType) -> str:
    MAP = {
        FieldType.STRING: "String",
        FieldType.INTEGER: "Int",
        FieldType.FLOAT: "Float",
        FieldType.BOOLEAN: "Boolean",
        FieldType.DATETIME: "DateTime",
        FieldType.TEXT: "String",
        FieldType.EMAIL: "String",
        FieldType.URL: "String",
        FieldType.JSON: "Json",
    }
    return MAP.get(ftype, "String")


def _field_to_typescript(ftype: FieldType) -> str:
    MAP = {
        FieldType.STRING: "string",
        FieldType.INTEGER: "number",
        FieldType.FLOAT: "number",
        FieldType.BOOLEAN: "boolean",
        FieldType.DATETIME: "Date",
        FieldType.TEXT: "string",
        FieldType.EMAIL: "string",
        FieldType.URL: "string",
        FieldType.JSON: "Record<string, any>",
    }
    return MAP.get(ftype, "string")


def _json_schema_to_ts(schema: dict) -> str:
    jtype = schema.get("type", "string")
    MAP = {
        "string": "string", "integer": "number", "number": "number",
        "boolean": "boolean", "array": "any[]", "object": "Record<string, any>",
    }
    return MAP.get(jtype, "any")


def _find_entity(graph: ArchitecturalGraph, name: str) -> EntityDef:
    for e in graph.entities:
        if e.name == name:
            return e
    return None


def _find_component(graph: ArchitecturalGraph, name: str) -> ComponentDef:
    for c in graph.components:
        if c.name == name:
            return c
    return None


def _find_id_field(entity: EntityDef):
    if not entity:
        return None
    for f in entity.fields:
        if f.name == "id":
            return f
    return None


def _route_to_filepath(path: str, method: HttpMethod) -> str:
    """Convert route path to Next.js App Router file path.

    /api/users → /users  (the 'api' prefix is handled by src/app/api/ directory)
    /api/users/:id → /users/[id]
    """
    clean = path.rstrip("/")
    # Strip leading /api since it's implicit in the src/app/api/ directory
    if clean.startswith("/api/"):
        clean = clean[4:]  # remove /api, keep the rest
    elif clean == "/api":
        clean = ""
    # Convert :param → [param] for Next.js dynamic routes
    parts = []
    for p in clean.split("/"):
        if p.startswith(":"):
            parts.append(f"[{p[1:]}]")
        else:
            parts.append(p)
    return "/".join(parts)


def _route_to_type_name(route: RouteDef) -> str:
    """Generate type name from route, e.g. /api/users POST → CreateUser"""
    parts = route.path.strip("/").split("/")
    entity = parts[-1] if parts[-1] and not parts[-1].startswith(":") else (parts[-2] if len(parts) > 1 else "Item")
    entity_singular = entity.rstrip("s") if entity.endswith("s") else entity
    entity_pascal = _capitalize(entity_singular)

    VERB_MAP = {
        HttpMethod.GET: "Get",
        HttpMethod.POST: "Create",
        HttpMethod.PUT: "Update",
        HttpMethod.PATCH: "Update",
        HttpMethod.DELETE: "Delete",
    }
    return f"{VERB_MAP.get(route.method, 'Handle')}{entity_pascal}"


def _guess_entity_from_route(route: RouteDef, graph: ArchitecturalGraph) -> EntityDef:
    """Guess which entity a route operates on from its path."""
    if route.queries_entities:
        return _find_entity(graph, route.queries_entities[0])
    parts = [p for p in route.path.strip("/").split("/") if not p.startswith(":") and p not in ("api",)]
    if parts:
        entity_name = _capitalize(parts[-1].rstrip("s"))
        entity = _find_entity(graph, entity_name)
        if entity:
            return entity
    return None


def _page_to_dir(path: str) -> str:
    """Convert page path to Next.js directory, e.g. /dashboard → /dashboard, /sutras/:id → /sutras/[id]"""
    clean = path.rstrip("/")
    parts = []
    for p in clean.split("/"):
        if p.startswith(":"):
            parts.append(f"[{p[1:]}]")
        else:
            parts.append(p)
    return "/".join(parts)


def _page_to_component_name(page: PageDef) -> str:
    """Generate component name from page path, e.g. /sutras/:id → SutraDetailPage"""
    path = page.path.strip("/")
    # Strip dynamic params (:id → id) and take the meaningful segments
    parts = []
    for p in path.replace("-", " ").replace("/", " ").split():
        if p.startswith(":"):
            parts.append(p[1:])  # strip colon
        else:
            parts.append(p)
    if len(parts) >= 2 and parts[-1] in ("id", "slug", "key"):
        # /sutras/:id → SutraDetail, /posts/:slug → PostDetail
        name = "".join(w.capitalize() for w in parts[:-1]) + "Detail"
    else:
        name = "".join(w.capitalize() for w in parts)
    return name + "Page"


def _format_default(val) -> str:
    if val is None:
        return "undefined"
    if isinstance(val, bool):
        return str(val).lower()
    if isinstance(val, str):
        return f'"{val}"'
    return str(val)


def _capitalize(s: str) -> str:
    if not s:
        return s
    return s[0].upper() + s[1:]


def _normalize_ts_type(ptype: str) -> str:
    """Normalize LLM-produced type strings to valid TypeScript types."""
    MAP = {
        "array": "any[]",
        "function": "() => void",
        "object": "Record<string, any>",
        "number": "number",
        "string": "string",
        "boolean": "boolean",
        "date": "Date",
        "any": "any",
        "void": "void",
    }
    ptype_lower = ptype.lower().strip()
    if ptype_lower in MAP:
        return MAP[ptype_lower]
    # If it ends with [], it's an array of some type
    if ptype.endswith("[]"):
        base = ptype[:-2]
        normalized_base = MAP.get(base.lower(), base)
        return f"{normalized_base}[]"
    return ptype


def _pluralize(name: str) -> str:
    """Naive pluralization — good enough for entity names."""
    if name.endswith("s") or name.endswith("x") or name.endswith("z") or name.endswith("ch") or name.endswith("sh"):
        return name + "es"
    if name.endswith("y") and len(name) > 1 and name[-2] not in "aeiou":
        return name[:-1] + "ies"
    return name + "s"
