// Generated by Void Manifest Engine
// Text input for searching sutras; calls onSearch with query string on change

'use client'

import { useState } from 'react'

interface SearchBarProps {
  onSearch: () => void
}

export default function SearchBar({ onSearch }: SearchBarProps) {
  const [query, setQuery] = useState<string>("")
  return (
    <div>
      {/* SearchBar: Text input for searching sutras; calls onSearch with query string on change */}
    </div>
  )
}