// Generated by Void Manifest Engine
// Displays sutra title, category, and a snippet of englishMeaning; links to detail page

'use client'

import { useState } from 'react'

interface SutraCardProps {
  sutra: Record<string, any>
}

export default function SutraCard({ sutra }: SutraCardProps) {
  return (
    <div className="rounded-lg border p-4 shadow-sm">
      {/* Displays sutra title, category, and a snippet of englishMeaning; links to detail page */}
      {/* sutra: {sutra} */}
    </div>
  )
}