// Generated by Void Manifest Engine
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'KnowledgeExplorer',
  description: 'A minimal, text-focused knowledge explorer app for browsing ancient Sutras',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-gray-900">
        {children}
      </body>
    </html>
  )
}
