// Generated by Void Manifest Engine
// Knowledge Explorer

import SearchBar from '@/components/SearchBar'
import CategoryFilter from '@/components/CategoryFilter'
import SutraList from '@/components/SutraList'

export default function Page() {
  return (
    <main className="container mx-auto p-4">
      <h1 className="text-2xl font-bold">Knowledge Explorer</h1>
      <p className="text-gray-600 mt-2">Home page with search, category filter, and list of sutras</p>
      <SearchBar />
      <CategoryFilter />
      <SutraList />
    </main>
  )
}