// Generated by Void Manifest Engine
// DO NOT EDIT BY HAND

export interface Sutra {
  id: number
  title: string
  sanskritText: string
  englishMeaning: string
  category: string
  createdAt: Date
  updatedAt: Date
  createdAt: Date
  updatedAt: Date
}

export interface SutraRelation {
  id: number
  sutraId: number
  relatedSutraId: number
  sutraId: string
  Sutra?: Sutra
  relatedSutraId: string
  Sutra?: Sutra
  createdAt: Date
  updatedAt: Date
}

// API request/response types
export interface GetSutraInput {
  search?: string
  category?: string
}

export interface GetSutraInput {
  id?: number
}

export interface GetCategorieInput {
}
